CREATE DATABASE UTILITY_DATA;
USE UTILITY_DATA;

CREATE TABLE UTILITY_JOBS(
JOB_ID INT PRIMARY KEY,
DATE_RAISED DATE,
DUE_DATE DATE,
COMPLETION_DATE DATE,
REGION VARCHAR(50),
AREA VARCHAR(100),
ENGINEER VARCHAR(100),
JOB_TYPE VARCHAR(100),
PRIORITY VARCHAR(100),
STATUS VARCHAR(30),
SLA_TARGET_HOURS INT,
ACTUAL_HOURS INT,
SLA_MET VARCHAR(10),
CUSTOMER_RATING DECIMAL(3,2),
COST DECIMAL(10,2),
DEPARTMENT VARCHAR(50),
RAISED_BY VARCHAR(50),
CASE_SOURCE VARCHAR(50)
);
SHOW DATABASES;
SHOW TABLES;

INSERT INTO UTILITY_JOBS
(
    JOB_ID,
    DATE_RAISED,
    DUE_DATE,
    COMPLETION_DATE,
    REGION,
    AREA,
    ENGINEER,
    JOB_TYPE,
    PRIORITY,
    STATUS,
    SLA_TARGET_HOURS,
    ACTUAL_HOURS,
    SLA_MET,
    CUSTOMER_RATING,
    COST,
    DEPARTMENT,
    RAISED_BY,
    CASE_SOURCE
)
VALUES
(
    1001,
    '2026-01-05',
    '2026-01-07',
    '2026-01-06',
    'North West',
    'Warrington',
    'John Smith',
    'Leakage',
    'High',
    'Completed',
    48,
    30,
    'Yes',
    5.0,
    450.00,
    'Operations',
    'Customer',
    'Phone'
);
SELECT * FROM UTILITY_JOBS;

SELECT JOB_ID,REGION,AREA,JOB_TYPE,PRIORITY FROM UTILITY_JOBS;
SELECT JOB_ID,REGION,AREA,JOB_TYPE,PRIORITY,STATUS FROM UTILITY_JOBS WHERE PRIORITY="HIGH";
SELECT JOB_ID,REGION,AREA,JOB_TYPE,PRIORITY,STATUS FROM UTILITY_JOBS WHERE PRIORITY="HIGH" AND REGION="NORTH WEST";
SELECT JOB_ID,REGION,AREA,JOB_TYPE,PRIORITY,ACTUAL_HOURS,STATUS FROM UTILITY_JOBS WHERE PRIORITY="HIGH" AND REGION="NORTH WEST" AND ACTUAL_HOURS>48;
SELECT JOB_ID,REGION,AREA,JOB_TYPE,PRIORITY,STATUS FROM UTILITY_JOBS WHERE PRIORITY="HIGH" OR PRIORITY="MEDIUM";
SELECT JOB_ID,REGION,AREA,JOB_TYPE,ACTUAL_HOURS,STATUS FROM UTILITY_JOBS WHERE ACTUAL_HOURS BETWEEN 24 AND 48;
SELECT JOB_ID,REGION,AREA,JOB_TYPE,PRIORITY,STATUS FROM UTILITY_JOBS WHERE REGION IN ("NORTH WEST", "YORKSHIRE", "NORTH EAST");
SELECT JOB_ID,REGION,AREA,JOB_TYPE,PRIORITY,STATUS FROM UTILITY_JOBS WHERE AREA LIKE "%MANCHESTER%";
SELECT JOB_ID,REGION,AREA,JOB_TYPE,PRIORITY,STATUS FROM UTILITY_JOBS WHERE PRIORITY="HIGH" AND AREA LIKE "%MANCHESTER%";
SELECT JOB_ID,REGION,AREA,JOB_TYPE,PRIORITY,COMPLETION_DATE,STATUS FROM UTILITY_JOBS WHERE COMPLETION_DATE IS NOT NULL;
SELECT COUNT(*) FROM UTILITY_JOBS;

SELECT COUNT(*) FROM UTILITY_JOBS WHERE PRIORITY="HIGH" AND COMPLETION_DATE IS NULL;
SELECT COUNT(*) FROM UTILITY_JOBS WHERE PRIORITY="HIGH" AND COMPLETION_DATE IS NOT NULL;

SELECT SUM(COST) FROM UTILITY_JOBS;
SELECT SUM(COST) FROM UTILITY_JOBS WHERE PRIORITY="HIGH";

SELECT AVG(ACTUAL_HOURS) FROM UTILITY_JOBS;
SELECT AVG(ACTUAL_HOURS) FROM UTILITY_JOBS WHERE PRIORITY="HIGH";

SELECT MIN(ACTUAL_HOURS) FROM UTILITY_JOBS;
SELECT MAX(ACTUAL_HOURS) FROM UTILITY_JOBS;
SELECT REGION, COUNT(*) FROM UTILITY_JOBS GROUP BY REGION;
SELECT DISTINCT REGION FROM UTILITY_JOBS;
SELECT DISTINCT AREA FROM UTILITY_JOBS;
SELECT REGION, COUNT(*) AS Total_Jobs FROM UTILITY_JOBS GROUP BY REGION;
SELECT COUNT(*) AS Missing_Region FROM UTILITY_JOBS WHERE REGION IS NULL;
SELECT COUNT(*) AS Blank_Region FROM UTILITY_JOBS WHERE TRIM(REGION)="";
SELECT REGION, COUNT(*) AS Total_Jobs FROM UTILITY_JOBS GROUP BY REGION ORDER BY Total_Jobs DESC;
SELECT JOB_ID, REGION FROM UTILITY_JOBS WHERE REGION <> "NORTH WEST";
SELECT JOB_TYPE, SUM(COST) FROM UTILITY_JOBS GROUP BY JOB_TYPE;
SELECT JOB_TYPE, AVG(ACTUAL_HOURS) FROM UTILITY_JOBS GROUP BY JOB_TYPE;
SELECT JOB_TYPE, COUNT(*) FROM UTILITY_JOBS WHERE PRIORITY="HIGH" GROUP BY JOB_TYPE;
SELECT JOB_TYPE, COUNT(*) FROM UTILITY_JOBS WHERE PRIORITY="HIGH" GROUP BY JOB_TYPE HAVING COUNT(*) > 20;
SELECT PRIORITY, COUNT(*) FROM UTILITY_JOBS GROUP BY PRIORITY;
SELECT PRIORITY, SUM(COST) FROM UTILITY_JOBS GROUP BY PRIORITY;
SELECT PRIORITY, AVG(ACTUAL_HOURS) FROM UTILITY_JOBS GROUP BY PRIORITY;
SELECT JOB_TYPE, SUM(COST) FROM UTILITY_JOBS GROUP BY JOB_TYPE ORDER BY SUM(COST) DESC LIMIT 3;
SELECT JOB_TYPE, COUNT(*) FROM UTILITY_JOBS GROUP BY JOB_TYPE HAVING COUNT(*) > 100;
SELECT JOB_TYPE, COUNT(*), AVG(ACTUAL_HOURS) FROM UTILITY_JOBS GROUP BY JOB_TYPE HAVING COUNT(*) >100 ORDER BY AVG(ACTUAL_HOURS) DESC LIMIT 3;
SELECT JOB_TYPE, AVG(CUSTOMER_RATING) FROM UTILITY_JOBS GROUP BY JOB_TYPE;
SELECT JOB_TYPE, AVG(CUSTOMER_RATING) FROM UTILITY_JOBS GROUP BY JOB_TYPE HAVING AVG(CUSTOMER_RATING) > 4.0 ;
SELECT JOB_TYPE, AVG(CUSTOMER_RATING) FROM UTILITY_JOBS GROUP BY JOB_TYPE ORDER BY AVG(CUSTOMER_RATING) DESC;
SELECT JOB_TYPE, SUM(COST), AVG(CUSTOMER_RATING) FROM UTILITY_JOBS GROUP BY JOB_TYPE HAVING AVG(CUSTOMER_RATING)> 4.0 ORDER BY SUM(COST) DESC LIMIT 5;
SELECT PRIORITY, AVG(ACTUAL_HOURS) FROM UTILITY_JOBS GROUP BY PRIORITY ORDER BY AVG(ACTUAL_HOURS) DESC;
SELECT PRIORITY, SUM(COST) FROM UTILITY_JOBS GROUP BY PRIORITY ORDER BY SUM(COST) DESC LIMIT 3;
SELECT JOB_TYPE, AVG(ACTUAL_HOURS) FROM UTILITY_JOBS GROUP BY JOB_TYPE HAVING AVG(ACTUAL_HOURS) >40;
SELECT ENGINEER, COUNT(*) FROM UTILITY_JOBS GROUP BY ENGINEER ORDER BY COUNT(*) DESC LIMIT 5;
SELECT ENGINEER, AVG(ACTUAL_HOURS) FROM UTILITY_JOBS GROUP BY ENGINEER ORDER BY AVG(ACTUAL_HOURS) DESC LIMIT 5;
SELECT JOB_TYPE, SUM(COST), COUNT(*), AVG(ACTUAL_HOURS) FROM UTILITY_JOBS GROUP BY JOB_TYPE ORDER BY SUM(COST) DESC LIMIT 5; 
  